# This is a basic workflow to help you get started with Actions

name: RELEASE_RC

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ release/rc ]
  pull_request:
    branches: [ release/rc ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: release commit
        run: ./plugin-script/release-rc.shs

      - name: patch envs
        run: |
          source ./envs/env.sh
          echo "EASY_YAPI_PR_TITLE=${EASY_YAPI_PR_TITLE}" >> $GITHUB_ENV
          echo "EASY_YAPI_PR_BODY=${EASY_YAPI_PR_BODY}" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "${{env.EASY_YAPI_PR_TITLE}}"
          body: "${{env.EASY_YAPI_PR_BODY}}"
          base: master
          labels: release

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
